CC = gcc
CFLAGS = -Wall -g

all: fsh testparse

fsh: fsh.o parse.o error.o
	gcc -g -o fsh fsh.o parse.o error.o

testparse: testparse.o parse.o error.o
	gcc -g -o testparse testparse.o parse.o error.o

clean:
	rm -f fsh fsh.o parse.o error.o testparse testparse.o a.out


# these lines generated by "gcc -MM *.c"
error.o: error.c error.h
fsh.o: fsh.c fsh.h parse.h error.h
parse.o: parse.c parse.h error.h
testparse.o: testparse.c parse.h error.h
